server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy Auth Service
    location /api/auth {
        proxy_pass http://auth-service:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location /api/profile {
        proxy_pass http://auth-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Menu Service
    location /api/menuitems {
        proxy_pass http://menu-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    location /api/categories {
        proxy_pass http://menu-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    location /images {
        proxy_pass http://menu-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Order Service
    location /api/orders {
        proxy_pass http://order-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    location /api/payments {
        proxy_pass http://order-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Inventory Service
    location /api/Inventory {
        proxy_pass http://inventory-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    location /api/inventory {
        proxy_pass http://inventory-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    location /api/inventory/predict {
        proxy_pass http://inventory-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Offer Service
    location /api/Offer {
        proxy_pass http://offer-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    location /api/offers {
        proxy_pass http://offer-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    location /api/offers/predict {
        proxy_pass http://offer-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Staff Service
    location /api/Staff {
        proxy_pass http://staff-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Java notifyService
    location /api/notifications {
        proxy_pass http://notify-service:8082;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}

